# Generated by Django 4.2.7 on 2023-11-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="name",
            field=models.CharField(default="Jack", max_length=50),
        ),
        migrations.AddField(
            model_name="student",
            name="student_id",
            field=models.IntegerField(default=0),
        ),
    ]
