# Generated by Django 4.2.7 on 2023-11-08 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("manager", "0003_remove_student_id_alter_student_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="login_date",
        ),
        migrations.AddField(
            model_name="student",
            name="description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
