# Generated by Django 4.2.7 on 2023-11-08 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0004_remove_student_login_date_student_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="student_id",
        ),
        migrations.AddField(
            model_name="student",
            name="usrname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
            preserve_default=False,
        ),
    ]
