# Generated by Django 4.2.7 on 2023-11-08 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0006_course_teacher_rename_description_student_bio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="user",
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_courses",
                to="manager.student",
            ),
        ),
    ]
