# Generated by Django 4.2.7 on 2023-11-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0007_remove_student_user_alter_enrollment_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_name",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="bio",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
