# Generated by Django 4.2.7 on 2023-11-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0008_course_course_name_alter_teacher_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseschedule",
            name="weekday",
            field=models.CharField(
                choices=[
                    ("Wed", "Wednesday"),
                    ("Thu", "Thursday"),
                    ("Fri", "Friday"),
                    ("Tue", "Tuesday"),
                    ("Sun", "Sunday"),
                    ("Sat", "Saturday"),
                    ("Mon", "Monday"),
                ],
                default="Mon",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="courseschedule",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="courseschedule",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
