# Generated by Django 4.2.7 on 2023-11-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0012_course_course_information_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="login_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="courseschedule",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (5, "Saturday"),
                    (6, "Sunday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (2, "Wednesday"),
                    (0, "Monday"),
                    (1, "Tuesday"),
                ],
                default=0,
            ),
        ),
    ]
