# Generated by Django 4.2.7 on 2023-11-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_student_login_time_alter_courseschedule_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='weekday',
            field=models.IntegerField(choices=[(6, 'Sunday'), (1, 'Tuesday'), (3, 'Thursday'), (2, 'Wednesday'), (0, 'Monday'), (5, 'Saturday'), (4, 'Friday')], default=0),
        ),
    ]
