# Generated by Django 4.2.7 on 2023-11-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_course_moodle_link_alter_courseschedule_weekday'),
        ('manager', '0016_alter_courseschedule_weekday'),
    ]

    operations = [
    ]
