# Generated by Django 4.2.7 on 2023-11-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_merge_20231122_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='weekday',
            field=models.IntegerField(choices=[(3, 'Thursday'), (2, 'Wednesday'), (0, 'Monday'), (6, 'Sunday'), (5, 'Saturday'), (1, 'Tuesday'), (4, 'Friday')], default=0),
        ),
    ]
