# Generated by Django 4.2.7 on 2023-11-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_alter_courseschedule_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='weekday',
            field=models.IntegerField(choices=[(4, 'Friday'), (0, 'Monday'), (2, 'Wednesday'), (5, 'Saturday'), (3, 'Thursday'), (6, 'Sunday'), (1, 'Tuesday')], default=0),
        ),
    ]
