# Generated by Django 4.2.7 on 2023-11-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0020_alter_courseschedule_weekday_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseschedule",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (5, "Saturday"),
                    (2, "Wednesday"),
                    (1, "Tuesday"),
                    (4, "Friday"),
                    (6, "Sunday"),
                    (3, "Thursday"),
                    (0, "Monday"),
                ],
                default=0,
            ),
        ),
    ]
