# Generated by Django 4.2.7 on 2023-11-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0022_course_message_alter_courseschedule_weekday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="message",
            field=models.CharField(
                blank=True,
                default="Remember to turn in your assignments on time!",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="courseschedule",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (1, "Tuesday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                    (2, "Wednesday"),
                    (0, "Monday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                ],
                default=0,
            ),
        ),
    ]
